changes

diff --git a/.deliver/config b/.deliver/config
--- a/.deliver/config
+++ b/.deliver/config
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+GIT_CLEAN_PATHS="_build rel priv/static"
+
+
 # 1. Give a name to your app
 
 APP="app"
@@ -46,6 +49,18 @@ pre_erlang_get_and_update_deps() {
     __sync_remote "
       ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
 
+    "
+  fi
+}
+
+pre_erlang_clean_compile() {
+    status "Running phoenix.digest" # log output prepended with "----->"
+  __sync_remote " # runs the commands on the build host
+      # [ -f ~/.profile ] && source ~/.profile # load profile (optional)
+      source ~/.profile
+      # echo \$PATH # check if rbenv is in the path
+      set -e # fail if any command fails (recommended)
+
       cd '$BUILD_AT'
 
       mkdir -p priv/static
@@ -61,6 +76,5 @@ pre_erlang_get_and_update_deps() {
       cd ..
 
       APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest $SILENCE
-    "
-  fi
+  "
 }
